# Generated by Django 3.1.8 on 2022-01-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dev_tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='틀 이름')),
                ('kind', models.CharField(max_length=30, verbose_name='틀 종류')),
                ('description', models.TextField(verbose_name='개발 툴 설명')),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='아이디어명')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='대표사진')),
                ('content', models.TextField(verbose_name='아이디어 설명')),
                ('interest', models.IntegerField(default=0, verbose_name='아이디어 관심도')),
                ('devtool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea.dev_tool')),
            ],
        ),
    ]
