# Generated by Django 3.1.8 on 2022-01-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='대표사진'),
        ),
    ]
