# Generated by Django 3.1.8 on 2022-01-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pirosta', '0002_auto_20220126_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='댓글내용')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pirosta.post', verbose_name='게시글')),
            ],
        ),
    ]
