# Generated by Django 4.0.1 on 2022-01-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='actor',
            field=models.CharField(max_length=200, verbose_name='배우'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.IntegerField(max_length=4, verbose_name='개봉년도'),
        ),
        migrations.AlterField(
            model_name='post',
            name='director',
            field=models.CharField(max_length=200, verbose_name='감독'),
        ),
        migrations.AlterField(
            model_name='post',
            name='genre',
            field=models.CharField(max_length=200, verbose_name='장르'),
        ),
        migrations.AlterField(
            model_name='post',
            name='running_time',
            field=models.IntegerField(verbose_name='러닝타임'),
        ),
        migrations.AlterField(
            model_name='post',
            name='star',
            field=models.FloatField(max_length=3, verbose_name='별점'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='리뷰'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
    ]
